on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - if: ${{ matrix.os == 'ubuntu-latest ' }}
        run: |
          ping -c 30 127.0.0.1

      # Clone
      - uses: actions/checkout@v4

      # Build
      - shell: bash
        run: ./build.sh

      # Test
      - shell: bash
        run: ./test.sh

      # Passed?
      - run: echo Yay, it passed!

      # Failed?
      - if: ${{ failure() }}
        run: echo Shit, it failed :(
